server:
  port: 9092

## database configuration
spring:
  application:
    name: HOTEL-SERVICE
  profiles:
    active: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microservices_t1
    username: postgres
    password: 3333
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:9096

# Okta security conf
okta:
  oauth2:
    issuer: https://dev-39211336.okta.com/oauth2/default	
    audience: api://default

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
